-- 1. Base Tables and Policies (from schema.sql)
-- Create profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  updated_at timestamp with time zone
);

-- Create tasks table
create table tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  status text default 'todo' check (status in ('todo', 'in_progress', 'done')),
  assignee_id uuid references profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table profiles enable row level security;
alter table tasks enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

create policy "Tasks are viewable by everyone." on tasks for select using ( true );
create policy "Authenticated users can create tasks." on tasks for insert with check ( auth.role() = 'authenticated' );
create policy "Users can update tasks." on tasks for update using ( true );

-- 2. Role and Status Enhancements (from schema_v2.sql)
-- Add role and status to profiles
alter table profiles 
add column if not exists role text default 'member' check (role in ('admin', 'member')),
add column if not exists status text default 'pending' check (status in ('active', 'pending', 'suspended'));

-- RLS Policies Update
-- Allow admins to update any profile (promotion/approval)
create policy "Admins can update any profile." 
on profiles for update 
using ( auth.uid() in ( select id from profiles where role = 'admin' ) );

-- Allow admins to delete profiles
create policy "Admins can delete profiles." 
on profiles for delete 
using ( auth.uid() in ( select id from profiles where role = 'admin' ) );

-- 3. Task Enhancements (from schema_v3.sql)
-- Add date fields to tasks
alter table tasks 
add column if not exists start_date timestamptz,
add column if not exists due_date timestamptz;
